export const AFFILIATE_ADS = {
    sidebar: [
        {
            title: "Logicool G PRO 2 LIGHTSPEED",
            description: "プロが選ぶ、超軽量ワイヤレスマウスの頂点。",
            badge: "おすすめ",
            price: "¥11,970",
            link: "https://amzn.to/4raGyQE",
            imageUrl: "https://m.media-amazon.com/images/I/51tqDjEoETL.jpg",
        },
        {
            title: "G PRO ゲーミングキーボード",
            description: "競技向け、コンパクトなテンキーレスデザイン。",
            badge: "人気",
            price: "¥10,480",
            link: "https://amzn.to/4rS8KJa",
            imageUrl: "https://m.media-amazon.com/images/I/61eSkWURkIL.jpg",
        },
        {
            title: "Radeon RX 9070 XT",
            description: "圧倒的なフレームレートで最高画質を体験。",
            badge: "NEW",
            price: "¥100,800",
            link: "https://amzn.to/4lcEiXU",
            imageUrl: "https://m.media-amazon.com/images/I/61WIPFSwJIL.jpg",
        },
        {
            title: "BIGBIG WON Gale Hall",
            description: "ホールエフェクトセンサー搭載。高精度なワイヤレスコントローラー。",
            badge: "人気",
            price: "¥5,999",
            link: "https://amzn.to/40LtJS4",
            imageUrl: "https://m.media-amazon.com/images/I/61bvjc0XiuL.jpg",
        },
        {
            title: "Flydigi Vader 4 PRO",
            description: "力切替トリガー搭載、究極の操作性を誇る多機能コントローラー。",
            badge: "プロ仕様",
            price: "¥10,404",
            link: "https://amzn.to/3N4v2s0",
            imageUrl: "https://m.media-amazon.com/images/I/61d-Tu3y-pL.jpg",
        }
    ],
    trending: [
        {
            title: "Razer Viper V3 Pro",
            description: "54gの超軽量設計、次世代の35Kセンサー搭載。プロゲーマー愛用率No.1マウス。",
            badge: "2025トレンド",
            price: "¥26,480",
            link: "https://www.amazon.co.jp/dp/B0D1B6NRT1",
            imageUrl: "https://m.media-amazon.com/images/I/51uIuGv-7RL.jpg",
        },
        {
            title: "SteelSeries Apex Pro TKL (2023)",
            description: "世界最速レベルのレスポンスを実現する可変アクチュエーションスイッチ。",
            badge: "最強キーボード",
            price: "¥24,800",
            link: "https://www.amazon.co.jp/dp/B0BFM2M19I",
            imageUrl: "https://m.media-amazon.com/images/I/71R7-Lw-D3L.jpg",
        },
        {
            title: "Logicool G PRO X SUPERLIGHT 2",
            description: "8Kポーリングレート対応に進化した、ワイヤレスマウスの完成形。",
            badge: "定番人気",
            price: "¥20,727",
            link: "https://www.amazon.co.jp/dp/B0CPHYT9X9",
            imageUrl: "https://m.media-amazon.com/images/I/61tPTe9rNUL.jpg",
        },
        {
            title: "MSI MAG 342CQR E2",
            description: "34インチのUWQHD湾曲モニター。180Hzで圧倒的な没入感のゲーム体験を。",
            badge: "限定モデル",
            price: "¥46,800",
            link: "https://www.amazon.co.jp/dp/B0D9S9M8L2",
            imageUrl: "https://m.media-amazon.com/images/I/71Z88qC-qRL.jpg",
        },
        {
            title: "Razer Huntsman V3 Pro TKL",
            description: "ラピッドトリガー搭載のアナログ光スイッチ。競技シーンに最適なスピード。",
            badge: "プロ仕様",
            price: "¥36,980",
            link: "https://www.amazon.co.jp/dp/B0CFQ7W4JF",
            imageUrl: "https://m.media-amazon.com/images/I/71Xm3o6XnML.jpg",
        },
        {
            title: "DualSense 1 Midnight Black",
            description: "PS5純正、ハプティックフィードバックで直感的なゲームプレイを可能に。",
            badge: "純正品質",
            price: "¥11,480",
            link: "https://www.amazon.co.jp/dp/B094R8KF9V",
            imageUrl: "https://m.media-amazon.com/images/I/61opD-S-YpL.jpg",
        },
        {
            title: "HyperX Cloud III",
            description: "快適な着け心地と高精細な音質。耐久性抜群のベストセラーヘッドセット。",
            badge: "快適設計",
            price: "¥12,000",
            link: "https://www.amazon.co.jp/dp/B0C3BVW694",
            imageUrl: "https://m.media-amazon.com/images/I/61k7W9Y-nGL.jpg",
        },
        {
            title: "Elgato Stream Deck MK.2",
            description: "15個のカスタムキーで操作を効率化。ライブ配信や作業の必須アイテム。",
            badge: "配信ツール",
            price: "¥20,680",
            link: "https://www.amazon.co.jp/dp/B09738CV2G",
            imageUrl: "https://m.media-amazon.com/images/I/61z-Y5W-pSL.jpg",
        },
        {
            title: "Logicool G915 TKL (G913)",
            description: "薄型メカニカルスイッチの最高峰。高級感のあるアルミニウム外装。",
            badge: "ハイエンド",
            price: "¥23,000",
            link: "https://www.amazon.co.jp/dp/B08B9P8Y2G",
            imageUrl: "https://m.media-amazon.com/images/I/71id-S-R-ZL.jpg",
        },
        {
            title: "Razer Wolverine V2 Pro",
            description: "競技向けワイヤレスコントローラー。超高速連射とカスタマイズ性が魅力。",
            badge: "ガチ勢向け",
            price: "¥24,800",
            link: "https://www.amazon.co.jp/dp/B0BRLS2NZM",
            imageUrl: "https://m.media-amazon.com/images/I/718y6o-YpLL.jpg",
        }
    ],
    gameDetail: {
        banner: {
            title: "REDMAGIC 11 Pro【日本公式】",
            description: "冷却ファン内蔵、最強のゲーミング体験をその手に。",
            badge: "最強スマホ",
            price: "¥129,800",
            link: "https://amzn.to/409mm6T",
            imageUrl: "https://m.media-amazon.com/images/I/61kKk5MyY6L.jpg",
        },
        sidebar: {
            title: "iPad (第10世代)",
            description: "創作もプレイも、この一台。究極의モバイルツール。",
            badge: "PICK UP",
            link: "https://amzn.to/4ucimQF",
            price: "¥58,800",
            imageUrl: "https://m.media-amazon.com/images/I/61opXmF-vsL.jpg",
        }
    }
};
